"use client";

import { useState } from "react";
import { type Vulnerability } from "../../lib/api";
import { SEVERITY_CONFIG } from "../styles";

interface PRCardProps {
  vuln: Vulnerability;
  index: number;
}

function PRCard({ vuln, index }: PRCardProps) {
  const cfg = SEVERITY_CONFIG[vuln.severity] ?? SEVERITY_CONFIG.LOW;
  const [showModal, setShowModal] = useState(false);

  const handleViewPR = () => {
    setShowModal(true);
  };

  const handleCloseModal = () => {
    setShowModal(false);
  };

  const handleCopyPRDescription = () => {
    const prDescription = `## 🔒 Security Fix: ${vuln.type.replace(/_/g, " ")}

**File:** \`${vuln.file}\`
**Line:** ${vuln.line}
**Severity:** ${vuln.severity}

### 🐛 Issue
${vuln.description}

### 💡 Proposed Fix
${vuln.fix_suggestion}

### 📝 Vulnerable Code
\`\`\`javascript
${vuln.code}
\`\`\`

### ✅ Testing
- [ ] Verify fix resolves the security issue
- [ ] Run existing test suite
- [ ] Add new security test case
- [ ] Manual security review

---
*Generated by CodeGuard AI - Powered by IBM WatsonX*`;

    navigator.clipboard.writeText(prDescription);
    alert("PR description copied to clipboard!");
  };

  return (
    <div className="pr-card" style={{ animationDelay: `${index * 80}ms` }}>
      <div
        style={{
          display: "flex",
          alignItems: "flex-start",
          justifyContent: "space-between",
          marginBottom: "0.75rem",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
          <div
            style={{
              width: 36,
              height: 36,
              borderRadius: "0.5rem",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              background: "rgba(99,102,241,0.15)",
              border: "1px solid rgba(99,102,241,0.2)",
            }}
          >
            <span
              className="material-symbols-outlined"
              style={{ color: "#818cf8", fontSize: 18 }}
            >
              alt_route
            </span>
          </div>
          <div>
            <p
              style={{
                fontSize: "0.875rem",
                fontWeight: 600,
                color: "#fff",
                lineHeight: 1.2,
                marginBottom: 2,
              }}
            >
              Fix {vuln.type.replace(/_/g, " ")}
            </p>
            <code
              style={{
                fontSize: "0.75rem",
                color: "#6b7280",
                fontFamily: "JetBrains Mono, monospace",
              }}
            >
              {vuln.file}:{vuln.line}
            </code>
          </div>
        </div>
        <span
          style={{
            fontSize: "0.7rem",
            padding: "2px 8px",
            borderRadius: 9999,
            fontWeight: 600,
            color: cfg.color,
            background: cfg.bg,
            whiteSpace: "nowrap",
          }}
        >
          Pending
        </span>
      </div>

      <p
        style={{
          fontSize: "0.75rem",
          color: "#6b7280",
          lineHeight: 1.6,
          marginBottom: "1rem",
        }}
      >
        {vuln.fix_suggestion}
      </p>

      <button
        onClick={handleViewPR}
        style={{
          width: "100%",
          padding: "0.5rem",
          borderRadius: "0.5rem",
          fontSize: "0.75rem",
          fontWeight: 600,
          color: "#818cf8",
          border: "1px solid rgba(99,102,241,0.2)",
          background: "transparent",
          cursor: "pointer",
          transition: "background 0.2s",
          fontFamily: "Inter, sans-serif",
        }}
        onMouseEnter={(e) =>
          (e.currentTarget.style.background = "rgba(99,102,241,0.1)")
        }
        onMouseLeave={(e) => (e.currentTarget.style.background = "transparent")}
      >
        View PR →
      </button>

      {/* PR Detail Modal - Enhanced Glassmorphism UI */}
      {showModal && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            background: "rgba(0,0,0,0.85)",
            backdropFilter: "blur(8px)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 1000,
            padding: "1rem",
            animation: "fadeIn 0.2s ease",
          }}
          onClick={handleCloseModal}
        >
          <div
            style={{
              background:
                "linear-gradient(135deg, rgba(30,30,35,0.95), rgba(20,20,25,0.98))",
              backdropFilter: "blur(20px)",
              border: "1px solid rgba(255,255,255,0.1)",
              borderRadius: "1.5rem",
              maxWidth: "700px",
              width: "100%",
              maxHeight: "85vh",
              overflow: "auto",
              padding: "2.5rem",
              position: "relative",
              boxShadow:
                "0 20px 60px rgba(0,0,0,0.5), 0 0 0 1px rgba(255,255,255,0.05)",
              animation: "slideUp 0.3s ease",
            }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              onClick={handleCloseModal}
              style={{
                position: "absolute",
                top: "1.5rem",
                right: "1.5rem",
                background: "rgba(255,255,255,0.08)",
                border: "1px solid rgba(255,255,255,0.1)",
                borderRadius: "50%",
                width: "40px",
                height: "40px",
                cursor: "pointer",
                color: "#fff",
                fontSize: "1.5rem",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                transition: "all 0.2s",
                fontFamily: "Inter, sans-serif",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background = "rgba(239,68,68,0.2)";
                e.currentTarget.style.borderColor = "rgba(239,68,68,0.3)";
                e.currentTarget.style.transform = "rotate(90deg)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = "rgba(255,255,255,0.08)";
                e.currentTarget.style.borderColor = "rgba(255,255,255,0.1)";
                e.currentTarget.style.transform = "rotate(0deg)";
              }}
            >
              ×
            </button>

            {/* Header */}
            <div style={{ marginBottom: "2rem" }}>
              <h2
                style={{
                  color: "#fff",
                  fontSize: "1.75rem",
                  fontWeight: 700,
                  marginBottom: "0.5rem",
                  fontFamily: "Inter, sans-serif",
                  display: "flex",
                  alignItems: "center",
                  gap: "0.75rem",
                }}
              >
                <span
                  style={{
                    fontSize: "2rem",
                    filter: "drop-shadow(0 0 8px rgba(99,102,241,0.5))",
                  }}
                >
                  🔒
                </span>
                Security Fix PR
              </h2>
              <p
                style={{
                  color: "#9ca3af",
                  fontSize: "0.875rem",
                  fontFamily: "Inter, sans-serif",
                }}
              >
                Auto-generated pull request for vulnerability remediation
              </p>
            </div>

            {/* Metadata Cards */}
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
                gap: "1rem",
                marginBottom: "2rem",
              }}
            >
              <div
                style={{
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  borderRadius: "0.75rem",
                  padding: "1rem",
                }}
              >
                <p
                  style={{
                    color: "#6b7280",
                    fontSize: "0.75rem",
                    fontWeight: 600,
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                    marginBottom: "0.5rem",
                  }}
                >
                  Type
                </p>
                <p
                  style={{
                    color: "#fff",
                    fontSize: "0.875rem",
                    fontWeight: 600,
                    fontFamily: "Inter, sans-serif",
                  }}
                >
                  {vuln.type.replace(/_/g, " ")}
                </p>
              </div>

              <div
                style={{
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  borderRadius: "0.75rem",
                  padding: "1rem",
                }}
              >
                <p
                  style={{
                    color: "#6b7280",
                    fontSize: "0.75rem",
                    fontWeight: 600,
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                    marginBottom: "0.5rem",
                  }}
                >
                  Location
                </p>
                <code
                  style={{
                    color: "#93c5fd",
                    fontSize: "0.875rem",
                    fontFamily: "JetBrains Mono, monospace",
                  }}
                >
                  {vuln.file}:{vuln.line}
                </code>
              </div>

              <div
                style={{
                  background: `${cfg.bg}15`,
                  border: `1px solid ${cfg.bg}40`,
                  borderRadius: "0.75rem",
                  padding: "1rem",
                }}
              >
                <p
                  style={{
                    color: "#6b7280",
                    fontSize: "0.75rem",
                    fontWeight: 600,
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                    marginBottom: "0.5rem",
                  }}
                >
                  Severity
                </p>
                <p
                  style={{
                    color: cfg.color,
                    fontSize: "0.875rem",
                    fontWeight: 700,
                    fontFamily: "Inter, sans-serif",
                  }}
                >
                  {vuln.severity.toUpperCase()}
                </p>
              </div>
            </div>

            {/* Issue Section */}
            <div
              style={{
                background: "rgba(239,68,68,0.05)",
                border: "1px solid rgba(239,68,68,0.15)",
                borderRadius: "1rem",
                padding: "1.5rem",
                marginBottom: "1.5rem",
              }}
            >
              <h3
                style={{
                  color: "#fff",
                  fontSize: "1rem",
                  fontWeight: 600,
                  marginBottom: "0.75rem",
                  fontFamily: "Inter, sans-serif",
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                }}
              >
                <span style={{ fontSize: "1.25rem" }}>🐛</span>
                Issue Description
              </h3>
              <p
                style={{
                  color: "#e5e7eb",
                  fontSize: "0.875rem",
                  lineHeight: 1.7,
                  fontFamily: "Inter, sans-serif",
                }}
              >
                {vuln.description}
              </p>
            </div>

            {/* Fix Section */}
            <div
              style={{
                background: "rgba(16,185,129,0.05)",
                border: "1px solid rgba(16,185,129,0.15)",
                borderRadius: "1rem",
                padding: "1.5rem",
                marginBottom: "1.5rem",
              }}
            >
              <h3
                style={{
                  color: "#fff",
                  fontSize: "1rem",
                  fontWeight: 600,
                  marginBottom: "0.75rem",
                  fontFamily: "Inter, sans-serif",
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                }}
              >
                <span style={{ fontSize: "1.25rem" }}>💡</span>
                Proposed Fix
              </h3>
              <p
                style={{
                  color: "#6ee7b7",
                  fontSize: "0.875rem",
                  lineHeight: 1.7,
                  fontFamily: "Inter, sans-serif",
                }}
              >
                {vuln.fix_suggestion}
              </p>
            </div>

            {/* Code Section */}
            <div style={{ marginBottom: "2rem" }}>
              <h3
                style={{
                  color: "#fff",
                  fontSize: "1rem",
                  fontWeight: 600,
                  marginBottom: "0.75rem",
                  fontFamily: "Inter, sans-serif",
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                }}
              >
                <span style={{ fontSize: "1.25rem" }}>📝</span>
                Vulnerable Code
              </h3>
              <pre
                style={{
                  background: "rgba(0,0,0,0.5)",
                  border: "1px solid rgba(255,255,255,0.08)",
                  padding: "1.25rem",
                  borderRadius: "0.75rem",
                  overflow: "auto",
                  fontSize: "0.8125rem",
                  color: "#fca5a5",
                  fontFamily: "JetBrains Mono, monospace",
                  lineHeight: 1.6,
                  maxHeight: "200px",
                }}
              >
                {vuln.code}
              </pre>
            </div>

            {/* Action Buttons */}
            <div style={{ display: "flex", gap: "1rem", flexWrap: "wrap" }}>
              <button
                onClick={handleCopyPRDescription}
                style={{
                  flex: 1,
                  minWidth: "200px",
                  padding: "1rem 1.5rem",
                  borderRadius: "0.75rem",
                  fontSize: "0.875rem",
                  fontWeight: 600,
                  color: "#fff",
                  background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                  border: "none",
                  cursor: "pointer",
                  fontFamily: "Inter, sans-serif",
                  transition: "all 0.2s",
                  boxShadow: "0 4px 12px rgba(99,102,241,0.3)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  gap: "0.5rem",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = "translateY(-2px)";
                  e.currentTarget.style.boxShadow =
                    "0 6px 20px rgba(99,102,241,0.4)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = "translateY(0)";
                  e.currentTarget.style.boxShadow =
                    "0 4px 12px rgba(99,102,241,0.3)";
                }}
              >
                <span style={{ fontSize: "1.125rem" }}>📋</span>
                Copy PR Description
              </button>
              <button
                onClick={handleCloseModal}
                style={{
                  padding: "1rem 1.5rem",
                  borderRadius: "0.75rem",
                  fontSize: "0.875rem",
                  fontWeight: 600,
                  color: "#9ca3af",
                  background: "rgba(255,255,255,0.05)",
                  border: "1px solid rgba(255,255,255,0.1)",
                  cursor: "pointer",
                  fontFamily: "Inter, sans-serif",
                  transition: "all 0.2s",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = "rgba(255,255,255,0.08)";
                  e.currentTarget.style.color = "#fff";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = "rgba(255,255,255,0.05)";
                  e.currentTarget.style.color = "#9ca3af";
                }}
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

interface PRCardsProps {
  vulnerabilities: Vulnerability[];
}

export default function PRCards({ vulnerabilities }: PRCardsProps) {
  const visible = vulnerabilities.slice(0, 6);

  return (
    <>
      <style>{`
        .pr-grid {
          display: grid;
          grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
          gap: 1rem;
          padding: 1.5rem;
        }
        .pr-card {
          background: rgba(255,255,255,0.02);
          border: 1px solid rgba(255,255,255,0.07);
          border-radius: 14px;
          padding: 1.25rem;
          transition: border-color 0.3s, transform 0.2s;
          animation: rowIn 0.4s ease both;
        }
        .pr-card:hover {
          border-color: rgba(99,102,241,0.3);
          transform: translateY(-2px);
        }
      `}</style>

      <div className="card">
        <div className="card-header">
          <span className="card-title">Auto-Generated PRs</span>
          <button
            style={{
              fontSize: "0.75rem",
              color: "#6366f1",
              fontWeight: 700,
              background: "none",
              border: "none",
              cursor: "pointer",
              fontFamily: "Syne, sans-serif",
            }}
          >
            View all →
          </button>
        </div>
        <div className="pr-grid">
          {visible.map((v, i) => (
            <PRCard key={`${v.file}-${v.line}-${i}`} vuln={v} index={i} />
          ))}
        </div>
      </div>
    </>
  );
}
