/**
 * REPORT EXPORTERS
 * Multiple export formats for analysis results
 * Supports JSON, CSV, Markdown, and HTML
 * 
 * @author Harshal - Team AVON
 */

'use strict';

/**
 * Export analysis results to various formats
 */
class ReportExporter {
  /**
   * Export to JSON format
   * @param {Object} results - Analysis results
   * @returns {String} JSON string
   */
  static toJSON(results) {
    return JSON.stringify(results, null, 2);
  }
  
  /**
   * Export vulnerabilities to CSV format
   * @param {Array} vulnerabilities - List of vulnerabilities
   * @returns {String} CSV string
   */
  static toCSV(vulnerabilities) {
    const headers = [
      'Type',
      'Severity',
      'Source File',
      'Source Line',
      'Sink File',
      'Sink Line',
      'Confidence',
      'Sanitized',
      'Fix Suggestion'
    ];
    
    const rows = vulnerabilities.map(v => [
      v.type,
      v.severity,
      v.dataFlow?.source?.file || 'N/A',
      v.dataFlow?.source?.line || 'N/A',
      v.dataFlow?.sink?.file || 'N/A',
      v.dataFlow?.sink?.line || 'N/A',
      v.confidence || 'N/A',
      v.dataFlow?.sanitized ? 'Yes' : 'No',
      (v.fix_suggestion || '').split('\n')[0].replace(/,/g, ';')
    ]);
    
    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');
    
    return csvContent;
  }
  
  /**
   * Export to Markdown format
   * @param {Object} results - Analysis results
   * @returns {String} Markdown string
   */
  static toMarkdown(results) {
    const date = new Date().toISOString().split('T')[0];
    const vulns = results.dataFlows?.flows || results.vulnerabilities || [];
    
    const critical = vulns.filter(v => v.severity === 'CRITICAL').length;
    const high = vulns.filter(v => v.severity === 'HIGH').length;
    const medium = vulns.filter(v => v.severity === 'MEDIUM').length;
    const low = vulns.filter(v => v.severity === 'LOW').length;
    
    let md = `# 🛡️ CodeGuard AI Security Audit Report\n\n`;
    md += `**Date:** ${date}\n`;
    md += `**Analysis Duration:** ${results.duration || 'N/A'}s\n`;
    md += `**Files Analyzed:** ${results.metadata?.fileCount || 'N/A'}\n\n`;
    
    md += `## 📊 Executive Summary\n\n`;
    md += `| Severity | Count |\n`;
    md += `|----------|-------|\n`;
    md += `| 🔴 Critical | ${critical} |\n`;
    md += `| 🟠 High | ${high} |\n`;
    md += `| 🟡 Medium | ${medium} |\n`;
    md += `| 🟢 Low | ${low} |\n`;
    md += `| **Total** | **${vulns.length}** |\n\n`;
    
    if (critical > 0) {
      md += `## 🔴 Critical Vulnerabilities\n\n`;
      vulns.filter(v => v.severity === 'CRITICAL').forEach((v, idx) => {
        md += `### ${idx + 1}. ${v.type}\n\n`;
        md += `**Description:** ${v.description}\n\n`;
        md += `**Data Flow:**\n`;
        md += `- Source: \`${v.dataFlow?.source?.file}:${v.dataFlow?.source?.line}\`\n`;
        md += `- Sink: \`${v.dataFlow?.sink?.file}:${v.dataFlow?.sink?.line}\`\n`;
        md += `- Confidence: ${(v.confidence * 100).toFixed(0)}%\n\n`;
        md += `**Fix:** ${v.fix_suggestion?.split('\n')[0]}\n\n`;
      });
    }
    
    md += `## 📈 Impact Analysis\n\n`;
    if (results.impact) {
      md += `- **Estimated Savings:** $${results.impact.estimated_savings_usd?.toLocaleString() || 'N/A'}\n`;
      md += `- **Risk Score:** ${results.impact.risk_score_total || 'N/A'}\n`;
    }
    
    md += `\n---\n\n`;
    md += `*Generated by CodeGuard AI - Team AVON*\n`;
    
    return md;
  }
  
  /**
   * Export to HTML format
   * @param {Object} results - Analysis results
   * @returns {String} HTML string
   */
  static toHTML(results) {
    const vulns = results.dataFlows?.flows || results.vulnerabilities || [];
    const date = new Date().toISOString().split('T')[0];
    
    const critical = vulns.filter(v => v.severity === 'CRITICAL').length;
    const high = vulns.filter(v => v.severity === 'HIGH').length;
    const medium = vulns.filter(v => v.severity === 'MEDIUM').length;
    
    return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CodeGuard AI Security Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
      background: #f5f5f5;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 30px;
      border-radius: 10px;
      margin-bottom: 30px;
    }
    .summary {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }
    .card {
      background: white;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .critical { border-left: 4px solid #dc2626; }
    .high { border-left: 4px solid #ea580c; }
    .medium { border-left: 4px solid #ca8a04; }
    .low { border-left: 4px solid #16a34a; }
    .vulnerability {
      background: white;
      padding: 20px;
      margin-bottom: 20px;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .badge {
      display: inline-block;
      padding: 4px 12px;
      border-radius: 12px;
      font-size: 12px;
      font-weight: 600;
      margin-right: 8px;
    }
    .badge-critical { background: #fee2e2; color: #dc2626; }
    .badge-high { background: #ffedd5; color: #ea580c; }
    .badge-medium { background: #fef3c7; color: #ca8a04; }
    code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 4px;
      font-family: 'Courier New', monospace;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🛡️ CodeGuard AI Security Audit Report</h1>
    <p>Date: ${date} | Files Analyzed: ${results.metadata?.fileCount || 'N/A'}</p>
  </div>
  
  <div class="summary">
    <div class="card critical">
      <h3>🔴 Critical</h3>
      <p style="font-size: 36px; margin: 0;">${critical}</p>
    </div>
    <div class="card high">
      <h3>🟠 High</h3>
      <p style="font-size: 36px; margin: 0;">${high}</p>
    </div>
    <div class="card medium">
      <h3>🟡 Medium</h3>
      <p style="font-size: 36px; margin: 0;">${medium}</p>
    </div>
    <div class="card">
      <h3>📊 Total</h3>
      <p style="font-size: 36px; margin: 0;">${vulns.length}</p>
    </div>
  </div>
  
  <h2>Vulnerabilities</h2>
  ${vulns.slice(0, 10).map(v => `
    <div class="vulnerability ${v.severity.toLowerCase()}">
      <div>
        <span class="badge badge-${v.severity.toLowerCase()}">${v.severity}</span>
        <strong>${v.type}</strong>
      </div>
      <p>${v.description}</p>
      <p><strong>Source:</strong> <code>${v.dataFlow?.source?.file}:${v.dataFlow?.source?.line}</code></p>
      <p><strong>Sink:</strong> <code>${v.dataFlow?.sink?.file}:${v.dataFlow?.sink?.line}</code></p>
      <p><strong>Confidence:</strong> ${(v.confidence * 100).toFixed(0)}%</p>
    </div>
  `).join('')}
  
  <footer style="text-align: center; margin-top: 40px; color: #666;">
    <p>Generated by CodeGuard AI - Team AVON</p>
  </footer>
</body>
</html>
`;
  }
  
  /**
   * Export to SARIF format (for GitHub Code Scanning)
   * @param {Array} vulnerabilities - List of vulnerabilities
   * @returns {String} SARIF JSON string
   */
  static toSARIF(vulnerabilities) {
    const sarif = {
      version: '2.1.0',
      $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
      runs: [{
        tool: {
          driver: {
            name: 'CodeGuard AI',
            version: '1.0.0',
            informationUri: 'https://github.com/AT512-dev/Team-AVON-Project-for-IBM-Hackathon'
          }
        },
        results: vulnerabilities.map(v => ({
          ruleId: v.type,
          level: this.severityToSARIFLevel(v.severity),
          message: {
            text: v.description
          },
          locations: [{
            physicalLocation: {
              artifactLocation: {
                uri: v.dataFlow?.source?.file || 'unknown'
              },
              region: {
                startLine: v.dataFlow?.source?.line || 1
              }
            }
          }]
        }))
      }]
    };
    
    return JSON.stringify(sarif, null, 2);
  }
  
  /**
   * Convert severity to SARIF level
   * @param {String} severity - Vulnerability severity
   * @returns {String} SARIF level
   */
  static severityToSARIFLevel(severity) {
    const mapping = {
      'CRITICAL': 'error',
      'HIGH': 'error',
      'MEDIUM': 'warning',
      'LOW': 'note'
    };
    return mapping[severity] || 'warning';
  }
}

module.exports = { ReportExporter };

// Made with Bob
